# Generated by Django 5.0 on 2024-07-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formContact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('formContact_surname', models.CharField(blank=True, max_length=250, null=True)),
                ('formContact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('formContact_comment', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
