# Generated by Django 5.0 on 2024-08-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_hours',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_week',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
